### ISSUE TITLE
Sending AT commands after connection

### ISSUE THREAD

**Issue by MatanTubul** [COUR4G3/python-pppd#5]
Hi,

How can i sent at commands to the serial port after i establish the connection?

**Comment by COUR4G3** [comment]
The only communication over serial happens here is in the chat script which
is handle by the chat program which is used to initialize the connection.

You could use some other Python library to then talk to the serial port, or
alternatively use 'chat' to send more AT commands. I was under the
impression the modem sends all RX/TX data to the remote side after the
connect but I could be mistaken.

Not entirely sure why you'd need to or want to do that?

**Comment by MatanTubul** [comment]
Thanks for your full answer.
